httpcaddyfile: Ensure handle_path is sorted as equal to handle
caddyserver/caddy pull request #3676
Opened 2020-08-21 05:49 UTC by francislavoie

I don't love this fix frankly, any hard-coded logic is 😬 but I'm not sure of a better way to do this. We want `handle` and `handle_path` to have different `dirFunc` logic, but we need them to sort equivalently because they are both just handles, where one is just a shortcut to the other.

Having done this, I think we could probably remove `handle_path` from the directive order since it'll never actually be seen by the sort function.

2020-08-21 06:08 UTC, francislavoie commented
I'm so confused. Why is `groupCounter` flaky? It adapts to `group3` on my machine but CI says it should be `group4`? 😬

2020-08-21 06:44 UTC, francislavoie commented
I hate Go's `map`. It sucks. 😠 

Well, now it should be deterministic. So that's helpful.

I ran 10k iterations of the adapt tests before/after to make sure.

2020-09-17 00:21 UTC, mholt requested changes
Just fixing a typo that was bothering me :)

Otherwise LGTM. I can see why this definitely isn't the most elegant fix, but it's pretty simple, hopefully it works well! If not, it's purely internal so we should be able to fix it up again if needed.

2020-09-17 00:21 UTC, mholt commented on caddyconfig/httpcaddyfile/httptype.go
> +	// we want to deterministicly loop over the set of dirs
```suggestion
	// we need to deterministically loop over each of these directives
```

2020-09-17 01:53 UTC, mholt commented on caddyconfig/httpcaddyfile/httptype.go
> +	// we need to deterministically loop over each of these directives
```suggestion
	// we need to deterministically loop over each of these directives
	// in order to keep the group numbers consistent
```

2020-09-17 01:53 UTC, mholt approved these changes
LGTM, I hate it. 🙃 

Actually though I think this is worth a shot. There are worse parts of the Caddyfile adapter's internals, so...

2020-09-17 02:01 UTC, merged