caddyfile: Add support for env var defaults, tests
caddyserver/caddy pull request #3682
Opened 2020-08-23 17:08 UTC by francislavoie

Closes #2313

This adds support for an optional default in Caddyfile environment variable placeholders with a `:-` separator. This is specifically for the ones like `{$FOO}`, not the ones like `{env.FOO}` which are replaced at runtime.

For example:

```
{$DOMAIN:-localhost} {
	respond "Hello world!"
}
```

If the `DOMAIN` environment variable exists, the site label will be set to the value of that environment variable, but if not set, will be set to `localhost`.

FYI @mholt I also noticed while working on this that we were doing `os.GetEnv` and feeding that into `os.ExpandEnv`, which actually means that the env var will be replaced twice in chain. I retained this behaviour for now and added a test for it, but it feels like that wasn't intentional. It would technically be a minor breaking change to fix it so I want to wait for your input.

2020-09-17 22:55 UTC, mholt requested changes
I guess I'm alright with this. Thanks!

Is the bash-ism `:-` just to keep things easier to remember so you don't have to learn a second syntax? (Because we're def. not bash)

As for the redundant ExpandEnv + Getenv, why is fixing it a breaking change?

Note the reviewdog comment

2020-09-17 23:04 UTC, francislavoie commented
> As for the redundant ExpandEnv + Getenv, why is fixing it a breaking change?

Someone could be specifically using that behaviour :man_shrugging: 

But if you're okay with fixing that, I can.

> Is the bash-ism `:-` just to keep things easier to remember so you don't have to learn a second syntax? (Because we're def. not bash)

I guess. What alternative syntax would you suggest?

2020-09-25 23:45 UTC, mholt commented
I am more familiar with `||` from several programming languages; JS actually uses that literally as a "otherwise" operator in some cases.

2020-11-01 23:29 UTC, francislavoie commented
How about `??`, as in the commonly used null coalescing operator? I think it's more technically correct because we only apply the default if the env doesn't exists, not if it's "falsey".

2020-11-02 22:21 UTC, mholt commented
I'd be fine with that too. Honestly I guess I don't care if it's `:-` or `??`. Should we put it to a vote? :P

2020-11-03 06:47 UTC, francislavoie commented
Alright decided to go ahead with `??`.

I also removed the "chaining" behaviour since I really doubt anyone actually relies on it, frankly. I just wanted to be safe by preserving it but it should be fine.

2020-11-16 22:11 UTC, mholt commented
I think `??` is fine.

> Also we have #3807 in the pipeline which uses ? for header defaults so I think ?? is likely natural to use here.

lol, I also just reopened this thread with the intent of linking to that issue. My OCD is bothered that one uses `?` and the other uses `??` but I'm not against it... still, might be worth asking... can we get them to be the same (`?`) -- would that make sense? Is it worth it?

2020-11-20 20:53 UTC, mholt commented
Now I have another idea. Doesn't something like `{$FOO:bar}` read a little more naturally/easier to you? Using `:` as the default operator in this sense. I feel like it reads easier, and reminds me more of ternary statements in a lot of languages, i.e. `A ? B : C` where `: C` indicates the default or fallback value.

Once I settle my mind on the syntax I'm good with merging this.

2020-11-20 21:17 UTC, francislavoie commented
Sure, that's fine to me. Just FYI, shell uses `:-` because it can also do other things followed by `:`, see https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

2020-11-23 19:50 UTC, mholt commented
K I've made up my mind, let's use `:` :smile: I'm done now, I promise we can merge this then.

2020-11-23 19:51 UTC, mholt approved these changes
Oh you already implemented it. K I guess we're good then.

2020-11-23 19:51 UTC, merged