caddyfile: support vars and vars_regexp matchers in the caddyfile
caddyserver/caddy pull request #3730
Opened 2020-09-17 01:27 UTC by Mohammed90

I noticed those were missing from the [Request Matcher docs of the Caddyfile](https://caddyserver.com/docs/caddyfile/matchers#path-regexp). I dug into the code and found they don't implement the necessary interface. Now they do.

2020-09-17 01:33 UTC, francislavoie commented
You beat me to it :joy: I was planning on doing this one soon, because these aren't actually useful until we have things that can set vars. I'm planning on setting up an `expression` HTTP handler that can set vars to arbitrary values using CEL :open_mouth:

2020-09-17 01:35 UTC, francislavoie submitted a review, later dismissed

2020-09-17 22:25 UTC, mholt requested changes
Ah yes... I remember now, I stopped before getting this far because I realized that these matchers were pretty limited in what they could do, and that the CEL matcher was probably a better, more flexible approach.

I'm not opposed to this though, and you've already gone ahead and done the work for it, so I'm open to merging this. Will this be useful?

(Thanks!)

2020-09-18 01:58 UTC, Mohammed90 commented on modules/caddyhttp/vars.go
> +		log.Printf("%+v\n\n", m)
“The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.” — Brian Kernighan 😄 But he didn't say keep it around 😅 will remove it

2020-09-18 02:12 UTC, Mohammed90 commented
> You beat me to it 😂 I was planning on doing this one soon

Dude, I'm trying to catch up! 😂 

> I'm not opposed to this though, and you've already gone ahead and done the work for it, so I'm open to merging this. Will this be useful?

I don't use them personally, but the vars_regexp can be powerful. It's effectively a wildcard matcher. This is why it was implemented initially, so I can use it in the [nginx-adapter to adapt the `if` directive](https://github.com/caddyserver/nginx-adapter/blob/bdbb6db7ff9ad6ceb0dcd93f89e396f6365aa5d4/if.go#L114-L144).

2020-09-25 23:46 UTC, mholt approved these changes
Thanks for implementing this. Anything else before we merge?

2020-09-25 23:48 UTC, Mohammed90 commented
> Thanks for implementing this. Anything else before we merge?

Nothing more, unless you have any review comments.

2020-09-25 23:50 UTC, merged

2020-09-25 23:50 UTC, mholt commented
Nope, thank you very much again! I'm sure that regexp one especially can be useful.