acme_server: switch to bbolt storage
caddyserver/caddy pull request #3868
Opened 2020-11-14 01:18 UTC by ViViDboarder

There have been some issues with the badger storage engine being used by the embedded acme_server. This will replace the storage engine with bbolt.

Fixes #3847
Closes #3849

2020-11-16 18:33 UTC, mholt commented
Thanks! Letsee... I think this is better than using badger, but I also don't think it solves this problem: https://github.com/caddyserver/caddy/issues/3865, since bolt also acquires an exclusive lock on a file. During reloads, Caddy will temporarily run two configurations at the same time to ensure the new config is valid and successful before closing the old one. So for a short time, two locks are required, or ideally, we find a way to transfer those the one lock to the new config, or share it, somehow.

In order for this fix to be complete, I think we'll have to make sure we reuse the same lock. Fortunately, Caddy has a facility for sharing such global state, called a [`UsagePool`](https://pkg.go.dev/github.com/caddyserver/caddy/v2#UsagePool). Basically, it's a reference-counting map. So you'd basically encode the CA configuration down to a string (could even be something as dumb as `fmt.Sprintf("%#v", authorityConfig)` -- because this value is purely internal, and can be as cryptic as a hash if we want) and then put it in the UsagePool. Then, on reload, the UsagePool would see that the value already exists and return that, rather than try to make a new one. Here's an example of how it's used: https://github.com/caddyserver/caddy/blob/13781e67ab1b2553598d0dd1a7153ce3cdbd4879/modules/caddyhttp/reverseproxy/reverseproxy.go#L221-L225

What do you think?

2020-11-16 18:46 UTC, ViViDboarder commented
Hmm. Interesting. I'll have to investigate a bit to see how this will work. Since this does resolve #3847, would it be ok to merge this without fixing #3865 and then fix that in a different branch? That would also limit the number of changes per branch.

2020-11-16 18:52 UTC, mholt requested changes
Fair enough, that sounds good to me.

However, I'd like to either keep the db path the same, and only delete it if it's badger; an easy way to detect this if it has a file called MANIFEST, I think. (Can you confirm that the bbolt implementation does not create a file called MANIFEST?)

2020-11-16 20:48 UTC, ViViDboarder commented
So `bbolt` creates a file rather than a directory, so it'll actually be pretty easy to detect and delete.

2020-11-16 22:40 UTC, ViViDboarder commented
Finished. I added a log line to let the user know something is being deleted. I could also remove it though.

For research towards the other issue, reloading with a changed config causes:

```
reload: sending configuration to instance: caddy responded with error: HTTP 400: {"error":"loading config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'acme_server': provision http.handlers.acme_server: initializing certificate authority: Error opening database of Type bbolt with source /Users/vividboarder/.local/share/caddy/acme_server/db: timeout"}
```

So it will indeed doing what you described above to fix #3865. I'll try to work on that next.

2020-11-18 21:59 UTC, mholt approved these changes
Great -- so my understanding is this is ready to merge, and your subsequent PR depends on this one. Should we merge this one in and then the next one (once it has finished the review process), or should we just roll them into one PR? What do you prefer?

2020-11-18 22:04 UTC, ViViDboarder commented
Let's see if I can get the other branch ready to go some time this week. If not, then it'd be nice to merge this so ARM folks can use the ACME server.

2020-11-23 20:03 UTC, merged

2020-11-23 20:04 UTC, mholt commented
Thank you for your help with this!!