httpcaddyfile: Fix unexpectedly removed policy
caddyserver/caddy pull request #4128
Opened 2021-04-22 15:09 UTC by skeetmtp

When user set on_demand tls option in a catch-all (:443) policy,
we expect other policies to not have the on_demand enabled
See ex in tls_automation_policies_5.txt

Btw, we can remove policies if they are **all** empty.

2021-04-22 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/caddyserver/caddy?pullRequest=4128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/caddyserver/caddy?pullRequest=4128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/caddyserver/caddy?pullRequest=4128) it.</sub>

2021-04-22 15:11 UTC, skeetmtp commented
For your information, the following txt show the current caddy behaviour : 
```
a.example.com {
}

b.example.com {
}

:443 {
	tls {
		on_demand
	}
}
----------
{
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"a.example.com"
									]
								}
							],
							"terminal": true
						},
						{
							"match": [
								{
									"host": [
										"b.example.com"
									]
								}
							],
							"terminal": true
						}
					]
				}
			}
		},
		"tls": {
			"automation": {
				"policies": [
					{
						"on_demand": true
					}
				]
			}
		}
	}
}
```

2021-04-22 15:14 UTC, skeetmtp commented
In the mean time, a workaround is to put a global tls option, so the "remove empty AP" loop do not do anything.
```

{
    email me@company.com
}
...
```

2021-04-22 15:47 UTC, francislavoie commented
Thanks -- please don't forget to sign the CLA https://github.com/caddyserver/caddy/pull/4128#issuecomment-824926843

2021-04-27 23:34 UTC, mholt requested changes
Thanks for the fix! Looks simple enough. Somewhere in the comments, we should refer to this PR. I made one suggestion for that.

2021-04-27 23:34 UTC, mholt commented on caddyconfig/httpcaddyfile/tlsapp.go
> +	// compute the number of empty policies (except subjects, of course)
```suggestion
	// compute the number of empty policies (disregarding subjects) - see #4128
```

2021-04-29 16:55 UTC, mholt approved these changes

2021-04-29 16:56 UTC, merged