httpcaddyfile: Fix sorting edgecase for nested `handle_path`
caddyserver/caddy pull request #4477
Opened 2021-12-12 17:37 UTC by francislavoie

Fixes a bug reported in https://caddy.community/t/handle-path-being-ignored-when-paired-with-handle-in-same-block/14393

We had some code in `ServerType.Setup()` that would ensure `handle_path` has the same sort level as `handle`, but we were missing the same check in `parseSegmentAsConfig` to make sure that works properly inside of any nested subroute (`handle`, `route`, `handle_errors`, `handle_response`).

2021-12-12 17:54 UTC, adityaxdiwakar commented
OP from the community thread, thank you very much @francislavoie. You guys are fast! Glad I switched to Caddy.

2021-12-13 17:42 UTC, mholt requested changes
Thanks for the fix. Hmm, unfortunate that we need to repeat that logic. I wonder if there's any way to combine the other function where this is from with this logic. :thinking:  (Maybe for another PR, if so.)

Can we move the change any lower? The only next use of `dir` is on L352, other than in an error message earlier on L349. It'd be helpful if the directive in the error message is the same as appears in the config. So I wonder if we move this change to between, say, L350-351 it might be a little more helpful.

2021-12-13 18:20 UTC, francislavoie commented
Yeah we should extract this to a method to do these kinds of normalizations. I'll move it.

2021-12-13 18:38 UTC, francislavoie commented
Updated

2021-12-13 18:40 UTC, mholt approved these changes
That looks better. Thanks!

2021-12-13 18:42 UTC, merged