Serve http2 when listener wrapper doesn't return *tls.Conn
caddyserver/caddy pull request #4929
Opened 2022-08-03 14:17 UTC by WeidiDeng

fixes [4921](https://github.com/caddyserver/caddy/issues/4921)

2022-08-04 17:26 UTC, mholt commented
Thanks for working on this!

So, my understanding of this is, that it allows us to serve HTTP/2 even if the underlying Conn is wrapped by a ListenerWrapper plugin so that if it's not a tls.Conn, it can still be recognized as one?

2022-08-05 00:05 UTC, WeidiDeng commented
> Thanks for working on this!
> 
> So, my understanding of this is, that it allows us to serve HTTP/2 even if the underlying Conn is wrapped by a ListenerWrapper plugin so that if it's not a tls.Conn, it can still be recognized as one?

Yes, because golang http.server won't directly serve http2 when return non tls.Conn, I have to manually configure [h2server](https://github.com/golang/go/issues/12737). tls.Conn still uses http.Server code path, because when handshake is not complete, it won't have "h2" as negotiated protocol.

2022-08-18 08:48 UTC, WeidiDeng commented
@mholt I noticed you don't allow serve [only http2](https://github.com/caddyserver/caddy/blob/c7772588bd44ceffcc0ba4817e4d43c826675379/modules/caddyhttp/app.go#L189), if you want, I can use http2.Server.ServeConn in this case.

2022-08-18 15:00 UTC, mholt commented
@WeidiDeng Yeah, we'd have to write our own HTTP server. I'm not sure I'm quite ready for that since it seems like a maintenance burden. You can see my attempt here: https://github.com/caddyserver/caddy/pull/4707#issuecomment-1204438638

I'll review this soon!

2022-08-19 00:32 UTC, WeidiDeng commented
@mholt I looked at you code, that's because http2.Server requires tls handshake to be complete, if there is any. To be fair, http2.Server can serve h2c with prior knowledge, that's like how currently reverse_proxy h2c transport is implemented.

But yes I agree it's a burden, especially if we are allowing serve http2 with non tls.Conn. Perhaps it's easier to configure tls nextproto directly, normal clients won't send h1 requests on a h2 tls.Conn.

2023-03-17 07:52 UTC, francislavoie commented
@WeidiDeng could you rebase this?

I'm not sure there's anything really blocking merging this. Seems like a reasonable fix for a usecase only used by caddy-l4 currently.

2023-03-17 08:06 UTC, WeidiDeng commented
@francislavoie I'll also need to update l4 listener module, that part is left as a todo.

There are some parts that I'm not sure, like using x/net/http2 instead of builtin http2, should there be an option?

2023-03-31 18:36 UTC, mholt requested changes
Thanks, I made a first pass and have some minor suggestions -- This looks like we're doing a lot more in-house but it opens up some new possibilities, yeah?

2023-03-31 18:36 UTC, mholt commented on modules/caddyhttp/server.go
> +	if r.TLS == nil {
Maybe a comment explaining what this block is used for

2023-03-31 18:36 UTC, mholt commented on modules/caddyhttp/server.go
> +	http2listeners []*http2Listener
```suggestion
	h2listeners []*http2Listener
```

Just for symmetry with `h3` vars I guess :)

2023-03-31 18:36 UTC, mholt commented on modules/caddyhttp/http2listener.go
> +type http2Listener struct {
A comment explaining the usefulness of this type instead of just the http2 package types would be useful!

2023-04-10 16:57 UTC, mholt approved these changes
Thanks @WeidiDeng  -- let's give this a try. Sorry for the long time on this. Thank you for your work!

2023-04-10 17:05 UTC, merged