optimization: Replaced strings.Index with strings.Cut
caddyserver/caddy pull request #4932
Opened 2022-08-04 09:31 UTC by chir4gm

modified:   cmd/main.go
	modified:   listeners.go
	modified:   modules/caddyhttp/reverseproxy/addresses.go
	modified:   modules/caddyhttp/reverseproxy/reverseproxy.go
	modified:   modules/caddyhttp/rewrite/rewrite.go

to fix Issue #4928

2022-08-04 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/caddyserver/caddy?pullRequest=4932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/caddyserver/caddy?pullRequest=4932) before we can accept your contribution.<br/><hr/>**Chirag Maheshwari** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/caddyserver/caddy?pullRequest=4932) it.</sub>

2022-08-04 17:17 UTC, francislavoie commented
Sorry, this has already been worked on here: https://github.com/caddyserver/caddy/pull/4930!

Thanks anyways.

2022-08-04 17:18 UTC, mholt commented
This PR appears to modify different files.

2022-08-04 17:23 UTC, mholt requested changes
Thanks for the contribution! This mostly looks good; just a few nits and a merge conflict to take care of first.

2022-08-04 17:23 UTC, mholt commented on listeners.go
> +	if before, after, found := strings.Cut(a, "/"); found {
This change has already been made in another PR.

2022-08-04 17:23 UTC, mholt commented on modules/caddyhttp/reverseproxy/addresses.go
> +		if before, after, found := strings.Cut(upstreamAddr, "/"); found {
This change has already been made in another PR.

2022-08-04 17:23 UTC, mholt commented on modules/caddyhttp/rewrite/rewrite.go
> -			// don't overwrite explicitly-configured query string
Restore the comments here, I think they are valuable

2022-08-04 17:23 UTC, mholt commented on modules/caddyhttp/rewrite/rewrite.go
> -
This empty line should probably remain since the comment above doesn't apply to these lines

2022-08-05 19:07 UTC, chir4gm commented
Hi, I'm new to OSS, but I have 'force' pushed a new commit with the requested changes after using `git reset` and modifying the `HEAD` commit on the `stringsFix` branch. Please tell me what to do in case something is wrong.

2022-08-05 19:12 UTC, mholt commented
@chir4gm Welcome to open source!

If you look at this page and scroll down you'll see "Conflicting files" and it has a link that says "command line" -- if you click that, instructions will appear about how to resolve conflicts.

Basically, changes were made to the same code in where you want to merge to, so you need to update your branch to figure out which changes should be the final result: yours or theirs.

2022-08-05 19:40 UTC, chir4gm commented
Got it! I think the other conflicting commit had semantically better variables. I hope the conflicts have been correctly resolved.

2022-08-05 20:39 UTC, mholt commented
Looks much better!

Now make sure to indent using tabs and not spaces. :)

2022-08-06 21:05 UTC, chir4gm commented
Hi, I manually made the formatting change. Quick question: When merging a pull request, can maintainers merge all of my commits from my branch into a single one?

2022-08-06 21:20 UTC, mholt approved these changes
> Hi, I manually made the formatting change. Quick question: When merging a pull request, can maintainers merge all of my commits from my branch into a single one?

Yes! We can "Squash and merge" and that's usually what we prefer to do here at the Caddy project, so you don't necessarily have to do that. There are a few occasions on larger PRs where multiple things are happening that we want to keep individual commits but that's pretty rare.

I'll merge this when CI is done. Thanks!

2022-08-07 04:03 UTC, merged