ci: set least privilged token for github actions
caddyserver/caddy pull request #5179
Opened 2022-10-31 07:21 UTC by boahc077

This PR sets minimum token permission for all workflow files in the repository. Currently, GitHub token has elevated access as demonstrated by the following GitHub Actions workflow run that was executed recently:
https://github.com/caddyserver/caddy/actions/runs/3352862992/jobs/5555290545#step:1:19

In addition to this PR, you should also consider setting the following permission so that new workflow files will default to read-only permissions:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository

Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>

2022-10-31 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/caddyserver/caddy?pullRequest=5179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/caddyserver/caddy?pullRequest=5179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/caddyserver/caddy?pullRequest=5179) it.</sub>

2022-10-31 08:04 UTC, francislavoie commented
IIRC we tried that, but it broke the release job since it needs to write to github releases. But I don't quite remember the details.

2022-11-01 22:08 UTC, mohammed90 requested changes
Francis is right. Write permission is need because we're publishing artifacts and posting release notes. Perhaps the only job where read-only is possible is the lint flow. I'd rather we don't touch the release flows without seeing evidence it won't break when the requested change is applied.

2022-11-02 01:29 UTC, boahc077 commented
Thanks @francislavoie and @mohammed90 for reviewing the PR! I have reverted the changes for all other workflow files. Please take a look.

2022-11-06 09:01 UTC, mohammed90 approved these changes
This is great! Thank you for this enhancement

2022-11-06 09:01 UTC, merged