caddyfile: Allow overriding server names
caddyserver/caddy pull request #5323
Opened 2023-01-20 07:24 UTC by francislavoie

Fix #5322

2023-01-21 04:41 UTC, IndeedNotJames requested changes
Breaks when two different servers are called the same:
```Caddyfile
{
	servers :443 {
		name https
	}

	servers :8000 {
		name https
	}
}

example.com {
}

:8000 {
}
```

```json
{
    "apps": {
        "http": {
            "servers": {
                "https": {
                    "listen": [
                        ":8000"
                    ]
                }
            }
        }
    }
}
```

2023-01-21 04:49 UTC, francislavoie commented
Ah right, I should reject duplicate names.

2023-01-21 05:04 UTC, IndeedNotJames approved these changes

2023-01-27 17:48 UTC, mholt approved these changes
Thanks. This is something I hoped we wouldn't really have to care about... but here we are. :sweat_smile:

2023-01-27 19:56 UTC, merged