use escaped path while rewriting
caddyserver/caddy pull request #5504
Opened 2023-04-20 09:58 UTC by TP-O

Fix #5278

Using unescaped path in rewriting makes me confuse which part after `?` is a query if the path contains `%3F`, so I thought it would be better to use an escaped path.

2023-04-20 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/caddyserver/caddy?pullRequest=5504) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/caddyserver/caddy?pullRequest=5504) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/caddyserver/caddy?pullRequest=5504) it.</sub>

2023-04-20 17:08 UTC, mholt commented
Thanks; this will need careful review, and in consideration with #5438.

2023-05-15 21:39 UTC, mholt requested changes
Honestly, I like the change. It's simpler code and all the exists tests still pass, along with two new test cases.

Do the test cases represent the original issue sufficiently?

Additionally, I wonder if @wlonkly could chime in and confirm that this patch works for you.

This is one of the few areas of the code that is more heavily tested, so I guess we can be confident with this, I'm just wary of unexpected edge cases especially if they relate to security issues :upside_down_face:

2023-05-15 21:39 UTC, mholt commented on modules/caddyhttp/rewrite/rewrite_test.go
> -
I usually leave a line break sometimes to weakly organize test cases into groups. It'd be convenient if we could preserve this line break.

2023-05-16 01:44 UTC, TP-O commented
> Honestly, I like the change. It's simpler code and all the exists tests still pass, along with two new test cases.
> 
> Do the test cases represent the original issue sufficiently?
> 
> Additionally, I wonder if @wlonkly could chime in and confirm that this patch works for you.
> 
> This is one of the few areas of the code that is more heavily tested, so I guess we can be confident with this, I'm just wary of unexpected edge cases especially if they relate to security issues upside_down_face

I think these test cases make sure the `Rewrite` function distinguishes between `%3F` and `?` when checking for query string after replacing.

2023-05-16 15:16 UTC, merged

2023-05-16 15:16 UTC, mholt commented
Thanks again for the contribution! If there are any issues reported we'll let you know :+1: