Fix file browser footer while in grid mode
caddyserver/caddy pull request #5536
Opened 2023-05-16 17:44 UTC by pistasjis

I looked at the new file browser template and found it to be pretty good looking. Nice job! I tried it locally and found that the footer looked something like this: 
![Screenshot 2023-05-16 at 19-38-12 samsungsd](https://github.com/caddyserver/caddy/assets/57069715/1c691ed7-3ee4-4e8e-bae7-def225a9e891)
The black space after the footer looks kinda awkward, so I decided to fix it. With this PR, it looks like this: 
![Screenshot 2023-05-16 at 19-38-43 samsungsd](https://github.com/caddyserver/caddy/assets/57069715/5cb8873d-3573-41a4-9933-1d1081f1dd07)

2023-05-16 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/caddyserver/caddy?pullRequest=5536) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/caddyserver/caddy?pullRequest=5536) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/caddyserver/caddy?pullRequest=5536) it.</sub>

2023-05-16 17:49 UTC, francislavoie commented
I think it looks better before, honestly. I don't think the footer should grow. It also stretches the gradient which causes worse color banding.

2023-05-16 18:05 UTC, mholt commented
Should the footer be stuck to the bottom (but not span the remaining height) instead?

2023-05-16 18:06 UTC, francislavoie commented
I suggest removing this:
```
@media (prefers-color-scheme: dark) {
	html {
		background: black; /* overscroll */
	}
```

This makes the gradient bg go all the the way to the bottom of the viewport.

2023-05-16 18:17 UTC, pistasjis commented
> ![image](https://user-images.githubusercontent.com/57069715/238735344-43bcb183-43df-41fd-9501-cc5d7b1ed1aa.png) Like this?

![image](https://github.com/caddyserver/caddy/assets/57069715/af418202-bed7-4f75-9318-8a41a1820dac)
Here's another where I set the background to the same as the grid view background. I'm not sure if it looks good or not though

2023-05-16 18:24 UTC, pistasjis commented
> > ![image](https://user-images.githubusercontent.com/57069715/238735344-43bcb183-43df-41fd-9501-cc5d7b1ed1aa.png) Like this?
> 
> ![image](https://user-images.githubusercontent.com/57069715/238736030-af418202-bed7-4f75-9318-8a41a1820dac.png) Here's another where I set the background to the same as the grid view background. I'm not sure if it looks good or not though

![image](https://github.com/caddyserver/caddy/assets/57069715/199dd0fc-60fe-42e8-87a1-bbc17bfaacc3)
I kinda like this one

2023-05-16 19:40 UTC, pistasjis commented
> > > ![image](https://user-images.githubusercontent.com/57069715/238735344-43bcb183-43df-41fd-9501-cc5d7b1ed1aa.png) Like this?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/57069715/238736030-af418202-bed7-4f75-9318-8a41a1820dac.png) Here's another where I set the background to the same as the grid view background. I'm not sure if it looks good or not though
> 
> ![image](https://user-images.githubusercontent.com/57069715/238737695-199dd0fc-60fe-42e8-87a1-bbc17bfaacc3.png) I kinda like this one

That being said, if you have color suggestions or another suggestion for how it should look, please tell me

2023-05-16 19:42 UTC, mholt commented
Sorry, just took a lunch break, and am about to run some errands -- I'll look at this again in a little bit :) Thanks!

2023-05-18 09:57 UTC, Skylerspencer approved these changes

2023-05-18 23:33 UTC, mholt requested changes
OK finally had a chance to clone this down and check it out. It definitely looks better, thanks!

I noticed, however, that it pushes the logo all the way to the bottom of the screen. I know I suggested this earlier, but on second thought I don't think it needs to be down there.

Turns out that this is fixed with just the 1 line of CSS.

IMO it looks good on my monitor (no banding that I can see). And I prefer to keep things simple.

If the suggestion is accepted we can just merge this in I think :+1:

2023-05-18 23:33 UTC, mholt commented on modules/caddyhttp/fileserver/browse.html
> +	top: 100vh;
```suggestion
```

2023-05-19 11:39 UTC, pistasjis commented on modules/caddyhttp/fileserver/browse.html
> +	top: 100vh;
Done

2023-05-19 15:51 UTC, merged

2023-05-19 15:51 UTC, mholt commented
Awesome, thank you for the contribution!! If we decide for some reason that the footer is best at the bottom, we know what to do now. :) Thanks again.

2023-05-19 16:01 UTC, mholt commented
@pistasjis Also, you may notice I just pushed bd34cb6b4e171567243ff541ca303ac32fec91d8 which adds a lot more filetypes for the icons.

2023-05-19 16:36 UTC, pistasjis commented
> @pistasjis Also, you may notice I just pushed [bd34cb6](https://github.com/caddyserver/caddy/commit/bd34cb6b4e171567243ff541ca303ac32fec91d8) which adds a lot more filetypes for the icons.

They look nice. I've used Tabler before and they're one of my favourite iconsets