fix: unwrap adapter modules to get underlying modules
caddyserver/caddy pull request #5624
Opened 2023-07-10 03:25 UTC by WeidiDeng

Fix [5621](https://github.com/caddyserver/caddy/issues/5621).

In addition, this also fixed several `add(remove)-package` related commands as they can't be used to add or remove adapter related modules.

Before,

![image](https://github.com/caddyserver/caddy/assets/28780594/5bdb06da-239b-43a8-93b3-c5a90c00d1ee)

After,

![image](https://github.com/caddyserver/caddy/assets/28780594/c8bdf1f1-ca2a-48db-9a59-3c851f71a488)

2023-07-10 03:42 UTC, mholt requested changes
Oh, thanks for this!

I was kind of thinking that we should rethink this command...

Technically, by "modules" I mean "config modules" i.e. an extension of the configuration.

I wonder if this command should actually be "list-plugins" to list all the plugins.

Or maybe the semantics shouldn't matter and we should just print everything.

The problem is that config adapters don't keep the same interface as a Caddy module... so we'd have to figure that out.

Can we talk about a fix where we don't wrap the adapters in the first place? I think I'd like that better. :grin:

2023-07-10 03:56 UTC, WeidiDeng commented
You mean adapters are not part of modules, and will not show as so. However, they will show in the new `list-plugin` command?

They are of course affected by add / remove package commands.

2023-07-10 03:57 UTC, WeidiDeng commented
What should be the definition of a plugin? Maybe just `config-adapters` are more expressive?

2023-07-10 04:10 UTC, mholt commented
Well, I'm not sure if a new `list-plugins` command is the right answer -- maybe it is. I need to think about it more, or maybe have a discussion about other good solutions.

2024-09-26 20:10 UTC, mholt commented
Revisiting this...

>  this also fixed several add(remove)-package related commands as they can't be used to add or remove adapter related modules.

Are you sure this doesn't work? It should still "plug in" the adapters and download the resulting build, even if they don't appear in the list.

I still hesitate to print adapters as if they were config modules with names like `caddy.adapters.*` because they aren't config modules. They're plugins, at least... but the list-modules command is for config modules.

I think perhaps there is a solution, but probably not this PR. I hope that's OK. Thank you for working on this nonetheless.

What I think we should do instead, to describe the config adapters supported by a Caddy build, is to properly set the Accept header in the admin API, since the Content-Type header is what determines which config adapters to use.

2024-09-26 20:11 UTC, closed without merging