export reverseproxy.ipVersions type
caddyserver/caddy pull request #5648
Opened 2023-07-22 17:42 UTC by kkroo

allows AUpstreams to be externally instantiable

2023-07-22 19:02 UTC, francislavoie commented
What kind of plugin are you writing that would need this? 🤔

2023-07-22 20:05 UTC, kkroo commented
dynamic configuration for a reverseproxy

2023-07-22 23:04 UTC, francislavoie commented
That doesn't really answer my question. Why are you calling this module from yours? What's the usecase? What problem are you solving?

2023-07-22 23:32 UTC, kkroo commented
I'm generating JSON configurations for a frontend reverse proxy, and the upstream uses an A record that is dynamic, so am using the `dynamic_upstreams` module to have control over the DNS resolver and caching. because the type is private, its not possible to instantiate a value and marshal the config correctly

2023-07-24 17:04 UTC, mholt commented
Interesting -- can you show us the code that needs this type? I'd rather keep it unexported if possible.

2023-07-24 17:06 UTC, mholt requested changes
If we do export this, the change LGTM mostly.

2023-07-25 11:26 UTC, kkroo commented
thanks for the review. 
here is a snippet of how this is being used:

```
proxyHandle := &reverseproxy.Handler{}
...
proxyHandle.DynamicUpstreamsRaw = caddyconfig.JSONModuleObject(
	reverseproxy.AUpstreams{
		Name:     upstreamHost,
		Port:     upstreamPort,
		Versions: &reverseproxy.IPVersions{IPv4: yes, IPv6: yes},
	}, "source", "a", &warn)
```

2023-07-25 18:11 UTC, mholt approved these changes
I don't _fully_ understand the use case for using the upstreams in other packages, but I think it's a good idea to export this anyway since it's used in an exported type. Hope it is useful :)

Thanks for the contribution!

2023-07-25 18:50 UTC, merged