core: Apply SO_REUSEPORT to UDP sockets
caddyserver/caddy pull request #5725
Opened 2023-08-09 15:17 UTC by mholt

For some reason, 10 months ago when I implemented SO_REUSEPORT
for TCP, I didn't realize, or forgot, that it can be used for UDP too. It is a
much better solution than using deadline hacks to reuse a socket, at
least for TCP.

Then https://github.com/mholt/caddy-l4/issues/132 was posted,
in which we see that UDP servers never actually stopped when the
L4 app was stopped. I verified this using this command:

    $ nc -u 127.0.0.1 55353

combined with POSTing configs to the /load admin endpoint (which
alternated between an echo server and a proxy server so I could tell
which config was being used).

I refactored the code to use SO_REUSEPORT for UDP, but of course
we still need graceful reloads on all platforms, not just Unix, so I
also implemented a deadline hack similar to what we used for
TCP before. That implementation for TCP was not perfect, possibly
having a logical (not data) race condition; but for UDP so far it
seems to be working. Verified the same way I verified that SO_REUSEPORT
works.

I think this code is slightly cleaner and I'm fairly confident this code
is effective.

2023-08-09 15:21 UTC, mholt commented
@WeidiDeng If you have a chance, we might want your review to ensure HTTP/3 still works properly through config reloads on Linux and Windows. (I don't have Windows)

2023-08-11 06:30 UTC, WeidiDeng commented
It doesn't work on windows 🤷‍♂️ . And there is a error log from [quic](https://github.com/quic-go/quic-go/blob/master/http3/server.go#L684).

![image](https://github.com/caddyserver/caddy/assets/28780594/ff5af4f2-11dd-46fa-8d45-0000670aa426)

2023-08-11 07:47 UTC, WeidiDeng requested changes
I added some debug output to http3 listener.

![image](https://github.com/caddyserver/caddy/assets/28780594/4a384956-cdde-46b7-9612-ae50e6b4da6c)

That error is related to `errFakeClosed` (emoji not displayed properly in powershell). This means quic listener (which is also shared) is still using the old packetconn (which is closed) instead of the new one (not closed).

2023-08-11 07:51 UTC, WeidiDeng commented
Maybe quic listener needs something similar to the tls.Config, but then again, `fakeCloseQuicListener` already does this job well enough.

2023-08-11 15:48 UTC, mholt commented on listen.go
> +	case "udp", "udp4", "udp6", "unixgram":
Oh, interesting. I didn't realize that. So I need to treat that as a unix socket instead.

2023-08-11 16:42 UTC, mholt commented
Aw man.

Thanks for your tests/analysis. I'll see what I can do to fix that up. I might have more questions for you :sweat_smile:

2023-10-10 21:12 UTC, francislavoie commented
Is this done? If not I think we should bump this to v2.7.6

2023-10-11 21:36 UTC, mholt commented
I think I might need @WeidiDeng 's help to finish this correctly. Bumping sounds good to me!

2023-10-13 07:58 UTC, WeidiDeng commented
I have tested this patch on linux and macos with [5749](https://github.com/caddyserver/caddy/pull/5749) and it's working fine, haven't tested it on windows though.

2023-10-16 20:36 UTC, mholt commented
@WeidiDeng Oof, I might have butchered the rebase. Do you think you could help me verify whether I did it correctly? :pleading_face:

2023-10-17 03:06 UTC, mholt commented
Thanks for the help again @WeidiDeng :smile: If you had a chance to try this and then review this as "approved" then I think I'll feel comfortable merging this in :+1:

2023-10-17 03:19 UTC, WeidiDeng approved these changes
LGTM

2023-10-17 04:17 UTC, merged