[Logging] Improve query filter for array of strings
caddyserver/caddy pull request #5779
Opened 2023-08-24 17:16 UTC by pauljeannot

As discussed in this [previous PR](https://github.com/caddyserver/caddy/pull/5101), here is the improvement to make the query filter handle array of strings.

This is needed so that the query filter can be used on headers, especially useful for the `Referer`.

**Disclaimer:** my first lines of code in Go, tried my best using the same logic and style that were used already. Successfully tested locally.

2023-08-24 17:52 UTC, mholt approved these changes
Very well done. :100: Especially for first Go code!

I'll let Francis give this a review but IMO this LGTM.

@francislavoie Should this be a bugfix or is this a feature? Wondering whether we should milestone this for 2.8 or 2.9.

2023-08-24 20:31 UTC, francislavoie commented
@mholt it really straddles the line. I think it's niche enough that it can be released as a bug fix with low risk.

2023-08-25 07:09 UTC, francislavoie approved these changes

2023-08-27 02:52 UTC, francislavoie commented
Before we merge this, this will need to inherit the same change from https://github.com/caddyserver/caddy/pull/5786 to fix a bug, otherwise modifying the `array` will modify the original request :grimacing:

2023-08-27 02:52 UTC, francislavoie requested changes
Before we merge this, this will need to inherit the same change from https://github.com/caddyserver/caddy/pull/5786 to fix a bug, otherwise modifying the `array` will modify the original request :grimacing:

2023-08-27 16:41 UTC, pauljeannot commented
Outch indeed! Changes made 🙏

2023-08-29 22:46 UTC, francislavoie requested changes

2023-08-29 22:46 UTC, francislavoie commented on modules/logging/filters.go
> +		in.Interface = newArray	} else {
```suggestion
		newArray := make(caddyhttp.LoggableStringArray, len(array))
		for i, s := range array {
			newArray[i] = m.processQueryString(s)
		}
		in.Interface = newArray
	} else {
```

2023-08-29 22:46 UTC, francislavoie commented on modules/logging/filters.go
> +	"golang.org/x/exp/slices"
```suggestion
```

2023-08-29 22:51 UTC, francislavoie approved these changes

2023-08-29 22:59 UTC, merged